// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/AliceOrlandini/Auto-Light-Pi/config"
	"github.com/AliceOrlandini/Auto-Light-Pi/controllers"
	"github.com/AliceOrlandini/Auto-Light-Pi/repositories"
	"github.com/AliceOrlandini/Auto-Light-Pi/routes"
	"github.com/AliceOrlandini/Auto-Light-Pi/services"
	"github.com/gin-gonic/gin"
)

// Injectors from injection.go:

func InitializeServer(ctx context.Context) (*gin.Engine, error) {
	db, err := ProvidePostgresDB(ctx)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	initialization := config.NewInitialization(userRepository, userService, userController)
	engine := routes.SetupRoutes(initialization)
	return engine, nil
}
