// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=mocks/mock_auth_controller.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	refresh_token "github.com/AliceOrlandini/Auto-Light-Pi/internal/refresh_token"
	user "github.com/AliceOrlandini/Auto-Light-Pi/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// GenerateJWT mocks base method.
func (m *MockauthService) GenerateJWT(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockauthServiceMockRecorder) GenerateJWT(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockauthService)(nil).GenerateJWT), userID)
}

// GenerateRefreshToken mocks base method.
func (m *MockauthService) GenerateRefreshToken(ctx context.Context, userID string) (*refresh_token.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", ctx, userID)
	ret0, _ := ret[0].(*refresh_token.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockauthServiceMockRecorder) GenerateRefreshToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockauthService)(nil).GenerateRefreshToken), ctx, userID)
}

// LoginByEmail mocks base method.
func (m *MockauthService) LoginByEmail(ctx context.Context, email, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginByEmail", ctx, email, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginByEmail indicates an expected call of LoginByEmail.
func (mr *MockauthServiceMockRecorder) LoginByEmail(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginByEmail", reflect.TypeOf((*MockauthService)(nil).LoginByEmail), ctx, email, password)
}

// LoginByUsername mocks base method.
func (m *MockauthService) LoginByUsername(ctx context.Context, username, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginByUsername", ctx, username, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginByUsername indicates an expected call of LoginByUsername.
func (mr *MockauthServiceMockRecorder) LoginByUsername(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginByUsername", reflect.TypeOf((*MockauthService)(nil).LoginByUsername), ctx, username, password)
}

// Register mocks base method.
func (m *MockauthService) Register(ctx context.Context, username, email, password, name, surname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password, name, surname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockauthServiceMockRecorder) Register(ctx, username, email, password, name, surname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthService)(nil).Register), ctx, username, email, password, name, surname)
}

// RotateRefreshToken mocks base method.
func (m *MockauthService) RotateRefreshToken(ctx context.Context, userID string) (*refresh_token.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, userID)
	ret0, _ := ret[0].(*refresh_token.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockauthServiceMockRecorder) RotateRefreshToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockauthService)(nil).RotateRefreshToken), ctx, userID)
}

// ValidateRefreshToken mocks base method.
func (m *MockauthService) ValidateRefreshToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockauthServiceMockRecorder) ValidateRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockauthService)(nil).ValidateRefreshToken), ctx, token)
}
