// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	refresh_token "github.com/AliceOrlandini/Auto-Light-Pi/internal/refresh_token"
	user "github.com/AliceOrlandini/Auto-Light-Pi/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// CreateOne mocks base method.
func (m *MockuserRepository) CreateOne(ctx context.Context, arg1 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOne", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOne indicates an expected call of CreateOne.
func (mr *MockuserRepositoryMockRecorder) CreateOne(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOne", reflect.TypeOf((*MockuserRepository)(nil).CreateOne), ctx, arg1)
}

// GetOneByEmail mocks base method.
func (m *MockuserRepository) GetOneByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByEmail indicates an expected call of GetOneByEmail.
func (mr *MockuserRepositoryMockRecorder) GetOneByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByEmail", reflect.TypeOf((*MockuserRepository)(nil).GetOneByEmail), ctx, email)
}

// GetOneByUsername mocks base method.
func (m *MockuserRepository) GetOneByUsername(ctx context.Context, username string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByUsername", ctx, username)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByUsername indicates an expected call of GetOneByUsername.
func (mr *MockuserRepositoryMockRecorder) GetOneByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByUsername", reflect.TypeOf((*MockuserRepository)(nil).GetOneByUsername), ctx, username)
}

// MockrefreshTokenRepository is a mock of refreshTokenRepository interface.
type MockrefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockrefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockrefreshTokenRepositoryMockRecorder is the mock recorder for MockrefreshTokenRepository.
type MockrefreshTokenRepositoryMockRecorder struct {
	mock *MockrefreshTokenRepository
}

// NewMockrefreshTokenRepository creates a new mock instance.
func NewMockrefreshTokenRepository(ctrl *gomock.Controller) *MockrefreshTokenRepository {
	mock := &MockrefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockrefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrefreshTokenRepository) EXPECT() *MockrefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateOne mocks base method.
func (m *MockrefreshTokenRepository) CreateOne(ctx context.Context, refreshToken *refresh_token.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOne", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOne indicates an expected call of CreateOne.
func (mr *MockrefreshTokenRepositoryMockRecorder) CreateOne(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOne", reflect.TypeOf((*MockrefreshTokenRepository)(nil).CreateOne), ctx, refreshToken)
}

// DeleteOneByUserID mocks base method.
func (m *MockrefreshTokenRepository) DeleteOneByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOneByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOneByUserID indicates an expected call of DeleteOneByUserID.
func (mr *MockrefreshTokenRepositoryMockRecorder) DeleteOneByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOneByUserID", reflect.TypeOf((*MockrefreshTokenRepository)(nil).DeleteOneByUserID), ctx, userID)
}

// GetOneTokenHashByUserID mocks base method.
func (m *MockrefreshTokenRepository) GetOneTokenHashByUserID(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneTokenHashByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneTokenHashByUserID indicates an expected call of GetOneTokenHashByUserID.
func (mr *MockrefreshTokenRepositoryMockRecorder) GetOneTokenHashByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneTokenHashByUserID", reflect.TypeOf((*MockrefreshTokenRepository)(nil).GetOneTokenHashByUserID), ctx, userID)
}

// GetOneUserIDByTokenHash mocks base method.
func (m *MockrefreshTokenRepository) GetOneUserIDByTokenHash(ctx context.Context, tokenHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneUserIDByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneUserIDByTokenHash indicates an expected call of GetOneUserIDByTokenHash.
func (mr *MockrefreshTokenRepositoryMockRecorder) GetOneUserIDByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneUserIDByTokenHash", reflect.TypeOf((*MockrefreshTokenRepository)(nil).GetOneUserIDByTokenHash), ctx, tokenHash)
}
